src/AppBundle/Form/ContactType.php
<?php

namespace AppBundle\Form;

use AppBundle\Model\ContactData;
use LB\UserBundle\Entity\User;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class ContactType
 * @package AppBundle\Form
 */
class ContactType extends AbstractType
{

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $choices = array("WEB" => "Web", "Android" => "Android", "IOS" => "IOS");

        $builder
            ->add('name', 'text', array('label' => 'contact.form.name', 'required' => true))
            ->add('email', 'email', array('label' => 'contact.form.email', 'required' => true))
            ->add('subject', 'text', array('label' => 'contact.form.subject'))
            ->add('userName', 'text', array('label' => 'contact.form.username', 'required' => true))
            ->add('device', 'choice', array('choices'=> $choices,'empty_value' => 'Choose your device', 'choices_as_values'=>true, 'label' => 'contact.form.device', 'required' => true))
            ->add('message', 'textarea', array('label' => 'contact.form.your_message', 'required' => true))
        ;
    }

    public function getName()
    {
        return 'contact_type';
    }
}

src/AppBundle/Form/DataTransformer/InterestsTransformer.php
<?php
/**
 * Created by PhpStorm.
 * User: pc-4
 * Date: 10/28/15
 * Time: 1:30 PM
 */

namespace AppBundle\Form\DataTransformer;

use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\TransformationFailedException;

class InterestsTransformer implements DataTransformerInterface
{
    private $manager;

    public function __construct(ObjectManager $manager)
    {
        $this->manager = $manager;
    }

    /**
     * Transforms an interests to an array
     *
     * @param mixed $interests
     * @return string
     */
    public function transform($interests)
    {
        if (null === $interests) {
            return '';
        }

        $interestsArray = [];
        foreach($interests as $interest){
            if (!isset($interestsArray[$interest->getGroup()->getId()])){
                $interestsArray[$interest->getGroup()->getId()] = [];
            }

            $interestsArray[$interest->getGroup()->getId()][$interest->getId()] = $interest->getId();
        }

        return $interestsArray;
    }

    /**
     * Transforms an array to interests.
     *
     * @param mixed $interestsArray
     * @return object|void
     */
    public function reverseTransform($interestsArray)
    {
        if (!$interestsArray) {
            return [];
        }

        $interestIds = [];
        foreach($interestsArray as $interestGroup){
            foreach($interestGroup as $key => $interest){
                $interestIds[] = $key;
            }
        }

        $interests = $this->manager
            ->getRepository('AppBundle:Interest')->findByIds($interestIds);

        return $interests;
    }
}

src/AppBundle/Form/LBGroupType.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\LBGroup;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * Class LBGroupType
 * @package AppBundle\Form
 */
class LBGroupType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'text', array('label' => 'group.form.name', 'required' => true, 'label_attr'=>array('class'=>'col-sm-5 col-md-4 control-label')))
            ->add('file', 'file', array('label' => 'group.form.group_image', 'required' => false, 'label_attr'=>array('class'=>'col-sm-5 col-md-4 control-label')))
            ->add('downloadLink', 'hidden', array('label' => 'group.form.group_image', 'required' => false, 'label_attr'=>array('class'=>'col-sm-5 col-md-4 control-label')))
            ->add('eventDate', 'datetime', array('date_widget' => "single_text", 'time_widget' => "single_text", 'label' => 'group.form.date', 'required' => true, 'label_attr'=>array('class'=>'col-sm-5 col-md-4 control-label')))
            ->add('joinLimit', 'integer', array('label' => 'group.form.limit_of_members', 'required' => false, 'label_attr'=>array('class'=>'col-sm-5 col-md-4 control-label')))
            ->add('description', 'textarea', array('label' => 'group.form.description', 'required' => true, 'label_attr'=>array('class'=>'col-sm-5 col-md-4 control-label')))
            ->add('address', 'hidden', array('required' => false, 'label_attr'=>array('class'=>'col-sm-5 col-md-4 control-label')))
            ->add('latitude', 'hidden', array('required' => false, 'label_attr'=>array('class'=>'col-sm-5 col-md-4 control-label')))
            ->add('longitude', 'hidden', array('required' => false, 'label_attr'=>array('class'=>'col-sm-5 col-md-4 control-label')))
            ->add('type', 'choice', array('label' => 'group.form.type', 'required' => true, 'label_attr'=>array('class'=>'col-sm-5 col-md-4 control-label'),
                'choices'=>array(LBGroup::GROUP_PUBLIC=>'group.form.public', LBGroup::GROUP_PRIVATE=>'group.form.private'),
                'placeholder' => 'group.form.choose_an_group_type'))
            ->add('submit', 'submit', array('label'=>'group.form.submit', 'attr'=>array('class'=>'btn btn-blue')))
        ;

    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'app_bundle_lbgroup_type';
    }
}

src/AppBundle/Form/LSoftAdManagerType.php
<?php
/**
 * Created by PhpStorm.
 * User: aram
 * Date: 10/31/16
 * Time: 4:11 PM
 */
namespace AppBundle\Form;

use AppBundle\Form\Type\LocationType;
use LB\UserBundle\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class LSoftAdManagerType
 * @package AppBundle\Form
 */
class LSoftAdManagerType extends AbstractType
{

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('gender', ChoiceType::class,
                array('choices' => User::$GENDER_CHOICE_FOR_I_AM, 'empty_value'=> 'All', 'required' => false))
            ->add('minAge')
            ->add('maxAge')
            ->add('city', LocationType::class, array('required' => false))
            ->add('interests')
        ;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\LSoftAdManager',
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'l_soft_ad_manager_type';
    }
}

src/AppBundle/Form/SearchType.php
<?php
/**
 * Created by PhpStorm.
 * User: pc-4
 * Date: 10/28/15
 * Time: 12:27 PM
 */

namespace AppBundle\Form;

use AppBundle\Form\DataTransformer\InterestsTransformer;
use LB\UserBundle\Entity\User;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class SearchType
 * @package AppBundle\Form
 */
class SearchType extends AbstractType
{
    protected $container;

    /**
     * @param Container $container
     */
    public function __construct(Container $container)
    {
        $this->container = $container;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        // get all interests
        $interests = $this->container->get('doctrine')->getRepository("AppBundle:interest")->findAll();

        // get all cities
        $cities = array('Yerevan', 'Moscow');


        $builder
            ->add('ageFrom', 'hidden')
            ->add('ageTo', 'hidden')
            ->add('interests', 'interests', array('data'=> $interests))
            ->add('skiAndRide')
            ->add('lookingFor', 'choice', array('choices' => User::$GENDER_CHOICE))
            ->add('city', 'choice', array('choices' => $cities))
            ->add('distance', 'integer', array('attr' =>array('placeholder' => 'MILES')))
            ->add('zipCode', 'text', array('attr' =>array('placeholder' => 'Zip code')))
            ->add('submit', 'submit')
        ;
    }

    public function getName()
    {
        return 'search_type';
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Model\SearchData',
        ));
    }
}

src/AppBundle/Form/Type/IconType.php
<?php
/**
 * Created by PhpStorm.
 * User: pc-4
 * Date: 10/27/15
 * Time: 5:30 PM
 */
namespace AppBundle\Form\Type;


use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class IconType extends AbstractType
{
    /**
     * @return null|string|\Symfony\Component\Form\FormTypeInterface
     */
    public function getParent()
    {
        return 'file';
    }
    /**
     * @return string
     */
    public function getName()
    {
        return 'icon_type';
    }
}

src/AppBundle/Form/Type/Interests.php
<?php
/**
 * Created by PhpStorm.
 * User: pc-4
 * Date: 10/27/15
 * Time: 5:30 PM
 */
namespace AppBundle\Form\Type;


use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class LeadLimit
 * @package AppBundle\Form\Type
 */
class Interests extends AbstractType
{
    protected $container;

    /**
     * @param Container $container
     */
    public function __construct(Container $container)
    {
        $this->container = $container;
    }

    /**
     * @return null|string|\Symfony\Component\Form\FormTypeInterface
     */
    public function getParent()
    {
        return 'text';
    }
    /**
     * @return string
     */
    public function getName()
    {
        return 'interests';
    }

    /**
     * @param FormView $view
     * @param FormInterface $form
     * @param array $options
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $em = $this->container->get('doctrine')->getManager();
        $interestGroups = $em->getRepository('AppBundle:InterestGroup')->findAllOrderByPosition();
        $view->vars['interestGroups'] = $interestGroups;
    }
}

src/AppBundle/Form/Type/LocationType.php
<?php
/**
 * Created by PhpStorm.
 * User: pc-4
 * Date: 10/27/15
 * Time: 5:30 PM
 */
namespace AppBundle\Form\Type;

use Symfony\Component\Form\AbstractType;

/**
 * Class LocationType
 * @package AppBundle\Form\Type
 */
class LocationType extends AbstractType
{
    /**
     * @return null|string|\Symfony\Component\Form\FormTypeInterface
     */
    public function getParent()
    {
        return 'text';
    }
    /**
     * @return string
     */
    public function getName()
    {
        return 'location_type';
    }
}

src/AppBundle/Resources/views/Form/form_label.html.twig
{% block form_label %}
    {% if not compound %}
        {% set label_attr = label_attr|merge({'for': id}) %}
    {% endif %}

    {% if required %}
        {% set label_attr = label_attr|merge({
            'class': (label_attr.class|default('') ~ ' required')|trim
        }) %}
    {% endif %}

    {% if label is empty %}
        {% set label = name|humanize %}
    {% endif %}

    <label
        {% for attrname, attrvalue in label_attr -%}
            {{ attrname }}="{{ attrvalue }}"
        {%- endfor %}
    >
        {{ label|trans({}, translation_domain) }}   {% if form.vars.required %}  <bdi class="text-red">*</bdi> {% endif %}

    </label>



{% endblock form_label %}

src/AppBundle/Resources/views/Form/icon.html.twig
{% block icon_type_widget %}
    {% set route = app.request.get('_route') %}
    {% set object = form.parent.vars.value %}

    {% set filename = object.filename %}
    {% if filename %}
        <img  height="{% if route == "admin_app_event_create" or route == "admin_app_event_edit" %}200{% else %}50{% endif %}" src="{{ object.downloadLink }}">
        <a href="{{ path('remove_image', {'filename' : filename, 'object' : object.className  }) }}"><span class="glyphicon glyphicon-remove"></span></a>
    {% else %}
        {{ form_widget(form) }}
    {% endif %}

{% endblock icon_type_widget %}

src/AppBundle/Resources/views/Form/interests.html.twig
{% block interests_widget %}
    {% for interestGroup in form.vars.interestGroups %}

        <div class="row">
            <div class="col-sm-12">
                <strong class="interest-title">{{ interestGroup.name }}<bdi> *</bdi></strong>
                <div class="row">
                    {% if interestGroup.name != "Areas I ski/ride most" %}
                        {% for interest in interestGroup.interest %}
                            <div class="col-sm-4 col-lg-3 overflow">
                                <label class="checkbox-inline">
                                    <input name="{{ form.vars.full_name }}[{{ interestGroup.id }}][{{ interest.id }}]"
                                           id="{{ form.vars.id }}[{{ interestGroup.id }}][{{ interest.id }}]"
                                           type="checkbox"
                                            {% if form.vars.value[interestGroup.id] is defined and form.vars.value[interestGroup.id][interest.id] is defined %}
                                    checked
                                            {% endif %}>{{ interest.name }}
                                </label>
                            </div>
                        {% endfor %}
                    {% else %}
                        {% set areaAndSki = generateAreAndSki(interestGroup) %}


                        <div id="ski-riding">

                        {% for group, interest in areaAndSki %}
                            {% if group |first == '_' %}
                                <div class="col-sm-12">
                                    <h4>{{ group }}</h4>
                                </div>
                            {% else %}
                                <div class="col-sm-4">
                                    <div class="checkbox-dropdown">
                                    {% if interest.image is defined %}<img src="{{ interest.image }}" height="20">{% endif %}
                                        &nbsp&nbsp{{ group }}
                                        <ul class="checkbox-dropdown-list">
                                            {% if interest.interests is defined%}
                                                {% for interestId, areaAndSky in interest.interests %}
                                                    <li>
                                                        <div class="checkbox">
                                                            <label>
                                                                <input name="{{ form.vars.full_name }}[{{ interestGroup.id }}][{{ interestId }}]"
                                                                       id="{{ form.vars.id }}[{{ interestGroup.id }}][{{ interestId }}]"
                                                                       type="checkbox"
                                                                        {% if form.vars.value[interestGroup.id] is defined and form.vars.value[interestGroup.id][interestId] is defined %}
                                                                            checked
                                                                        {% endif %}
                                                                        >{{ areaAndSky }}
                                                            </label>
                                                        </div>

                                                    </li>
                                                {% endfor %}
                                            {% endif %}

                                        </ul>
                                    </div>

                                </div>
                            {% endif %}

                        {% endfor %}
                        </div>

                    {% endif %}
                </div> <br />
            </div>
        </div>
    {% endfor %}
{% endblock %}

src/AppBundle/Resources/views/Form/interestsForSearch.html.twig
{% block interests_widget %}
    {% set selected = form.parent.vars.value.interests %}

      {% for key, interestGroup in form.vars.interestGroups %}
          {% if interestGroup.name != "Areas I ski/ride most" %}
                <div class="form-group">
                    <select class="form-control interest-select interest-select{{ key }}"
                            data-placeholder="{{ interestGroup.name }}"
                            data-init="{{ selected|json_encode }}"
                            multiple="multiple">
                        {% for interest in interestGroup.interest %}
                            <option {% if interest.id in selected  %} selected {% endif %} value="{{ interest.id }}">{{ interest.name }}</option>
                        {% endfor %}
                    </select>
                </div>
        {% else %}
            <div class="form-group">

                {% set areaAndSki = generateAreAndSki(interestGroup) %}

                <select class="ski-and-riding-responsive form-control interest-select"  multiple="multiple"
                        data-init="{{ selected|json_encode }}"
                        data-placeholder="{{ interestGroup.name }}">
                    {% for group, interest in areaAndSki %}
                        {% if interest.image is defined %}
                        <optgroup label="{{ group }}" data-image="{{ interest.image }}">
                        {% endif %}
                        {% if interest.interests is defined%}
                            {% for id, interestName in interest.interests %}
                                <option {% if id in selected  %} selected {% endif %} value="{{ id }}">{{ interestName }}</option>
                            {% endfor %}
                        {% endif %}
                        {% if interest.image is defined %}
                        </optgroup>
                        {% endif %}
                    {% endfor %}
                </select>

            </div>
        {% endif %}
    {% endfor %}
{% endblock %}

src/AppBundle/Resources/views/Form/location.html.twig
{% block location_type_widget %}
{% set route = app.request.get('_route') %}

    <div data-ng-app="Ads" data-ng-controller="AdsGeoController">

        <input type="text"
               data-google-places-autocomplete
               data-place="place"
               class="form-control"
               {% if route == "admin_lsoft_ad_ad_edit" or route == "admin_lsoft_ad_ad_create"%}
                   data-types="['(cities)']"
                   data-ng-init="isAddManager = true"
                {% if form.parent.vars.value %}
                    value="{{ form.parent.vars.value.city }}"
                {% endif %}
               {% endif %}
                {% if route == "admin_app_event_create" or route == "admin_app_event_edit" %}
                    data-ng-init="isEventManager = true;markersClickable = false{% if form.parent.vars.value and form.parent.vars.value.city %};initEventLocation({{ form.parent.vars.value.cityLat }},{{ form.parent.vars.value.cityLng }},'{{ form.parent.vars.value.city }}')"
                    value="{{ form.parent.vars.value.city }}
                    {% endif %}
                    "
                {% endif %}
               style="margin-bottom:5px"/>

        {% if route != "admin_lsoft_ad_ad_edit" and route != 'admin_lsoft_ad_ad_create' %}
            <div data-simple-map-marker
                 data-map-click="markersClickable"
                 data-init-markers="{{ form.parent.vars.value.getLocationsJson|default('') }}"
                 data-storage="markersStorage"
                 class="map"
                 style="width: 100%; height: 400px">
            </div>
        {% endif %}

        <input id="{{ form.vars.id }}" name="{{ full_name }}" type="hidden" class="markers-storage" value="[[ markersStorage | groups ]]">
    </div>

    <script src="{{ asset('app/bower_components/angular/angular.min.js') }}"></script>
    <script src="{{ asset('app/scripts/Google/Google.js') }}"></script>
    <script src="{{ asset('bundles/app/js/angular/ads.js') }}"></script>
    {% if route == "admin_app_event_create" or route == "admin_app_event_edit" %}
        <script src="{{ asset('bundles/app/js/event.js') }}"></script>
    {% endif %}

    {% if route != "admin_lsoft_ad_ad_edit" and route != "admin_lsoft_ad_ad_create" %}<script src="https://maps.googleapis.com/maps/api/js?libraries=places&language=en&v=3&key={{ google_browser_api_key }}"></script>{% endif %}
{% endblock location_type_widget %}